backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images

collections:
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "settings.yml"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "url"
            widget: "string"
          - label: "Global title"
            name: "site_title"
            widget: "string"
          - label: "Global description"
            name: "site_description"
            widget: "string"
          - label: "Category visible"
            name: "category_visible"
            widget: "boolean"
            default: true
          - label: "Tag visible"
            name: "tag_visible"
            widget: "boolean"
            default: true

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Description"
                name: "description"
                widget: "markdown"
      - name: "categories"
        label: "Categories"
        file: "categories.yml"
        description: "List of categories"
        fields:
          - name: categories
            label: Categories
            label_singular: "Category"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the category"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Category name for displaying on the site"
      - name: "tags"
        label: "Tags"
        file: "tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: Category
        name: "category"
        widget: relation
        collection: "meta"
        file: "categories.yml"
        searchFields:
          - "categories.*.name"
        displayFields:
          - "categories.*.name"
        valueField: "categories.*.slug"
